#!/bin/bash

declare -i min
declare -i max

# Default colors (values are in sixel format):
colors=(
	[0]="18;20;23"
	[1]="6;28;16"
	[2]="0;43;20"
	[3]="15;65;26"
	[4]="22;83;33"
)

input=( $(cat -) )

# Find min and max input values.
for val in "${input[@]}"; do

	# Remove non-integer values.
	if [[ ! $val =~ ^-?[0-9]+$ ]]; then
		input=( "${input[@]/$val}" )
		continue
	fi

	if [[ ! -v min ]] || (( $val < $min )); then
		min=$val
	fi
	if [[ ! -v max ]] || (( $val > $max )); then
		max=$val
	fi
done

# Divide $1 by $2 and round the result to the nearest integer.
divide() {
	numerator=$1
	denominator=$2

	echo "$(( (numerator + denominator/2) / denominator ))"
}

# Map input values to color codes.
cells=( )
range=$(( max - min ))
max_color_code=$(( ${#colors[@]} - 1 ))
for val in "${input[@]}"; do
	cells+=( "$( divide $(( (val - min)*max_color_code )) range )" )
done
